INSERT INTO MOOD_METER_USER (USER_ID, USER_NAME) VALUES (2, 'foo'), (3, 'bar');
INSERT INTO MOOD_METER_TEAM (TEAM_ID, TEAM_NAME, TEAM_LINK, TEAM_OWNER_USER_ID) VALUES (2, 'Igel', 'BHudSkj9nO2O09i7pXWlcQ==', 2);
INSERT INTO MOOD_METER_QUESTION (QUESTION_ID, QUESTION) VALUES (3, 'Wie hat dir die Bearbeitung der Aufgaben im Sprint gefallen?');
